### PR TITLE
Python bindings

### PR DESCRIPTION
**Pull request by hsorby**
Hi @MichaelClerx I think this is more the way we should go with the bindings.  We'll let SWIG do the main work and then use typemaps for things that don't crossover so well.

### CODE REVIEW

**Review by MichaelClerx — APPROVED** [review]

**Comment by MichaelClerx** [comment]
Thanks @hsorby !
Only issue is it makes for a very cumbersome Python interface: the libcellml module is empty, the libcellml.entity module only contains a single class...
Is there an obvious way to fix this? For example, we could alias all those methods in the main libcellml module (much like numpy/scipy do) or write a Python-only wrapper module that uses the generated libcellml one?

**Comment by hsorby** [comment]
So what I'm expecting and going for here is an interface that matches the C++ interface as closely as possible.  I'm not personally in favour of lumping everything into one module and follow the idea that everything should be explicitly included.  I wouldn't ever expect to see statements like

```
from libcellml import *
```

Each module that we create with SWIG should only have the modules information that is making it similar to the C++ header files.

**Comment by MichaelClerx** [comment]
I'm not advocating an import * here. But having a separate module for every class is a very strange way of doing things. The whole point of a module is that it's a container for related classes, methods, etc.

So Python users would expect something like

```
import libcellml
x = libcellml.Units()
y = libcellml.Model()
z = libcellml.Component()
```

Not

```
import libcellml
import libcellml.units
import libcellml.model
import libcellml.component

x = libcellml.unit.Units()
y = libcellml.model.Model()
z = libcellml.component.Component()
```

I understand keeping the Python wrappers similar to the C++ structure is easy for development, but users wont care about that!


Update: Just tagging you cause I'm not sure you get notifications about these comment-based discussions @hsorby  :-)

**Comment by hsorby** [comment]
I think this can easily be achieved with manipulating the libcellml package file.  We can in fact have both ways.

This should be raised as an issue on cellml/libcellml.  Then everyone who cares can have a say on the way the libCellML Python package and modules should be laid out.

**Pull request merged**
