### PR TITLE
Fixes for running tests on Windows.

### PR DESCRIPTION
**Pull request by hsorby**

### CODE REVIEW

**Comment by MichaelClerx** [comment]
The first three commits shouldn't be there!

**Comment by MichaelClerx** [comment]
Guessing you continued from your local branch? The current branch has your first three commits in rebased form, plus one of mine. Maybe drop the pull request, rebase and start again?

**Comment by hsorby** [comment]
I don't mind having these extra commits.  I think rebasing only leads to problems especially if you do it after some has pulled your work.  I have made another pull request.

**Comment by hsorby** [comment]
Re-done in #5.

**Comment by MichaelClerx** [comment]
I like rebasing, it makes for a much more readable commit history than lots of branches and merging

**Comment by MichaelClerx** [comment]
Either way, you need to make sure your local git repo is up to date with this one before you create PRs - just like you do when you push - instead of relying on automatic merge to get things right.

**Comment by nickerso** [comment]
One issue is that some (most?) of us have no idea what rebasing is, does or how to cope with it when we want to try and contribute to each other's topic branches...branch and merge is something that we are all familiar with and can understand :)

**Comment by hsorby** [comment]
Rebasing is fine if you do it properly if you are rebasing when other developers are working on the same branch it does not work well and makes more work for others.

**Comment by MichaelClerx** [comment]
If you all prefer branches & merges then I'll go with that. If you go out of sync with a branch you want to contribute to I'd still always rebase to its new HEAD first, so you can commit without a merge. That would have prevented this issue anyway.

@hsorby @nickerso For merging PRs, is squashing ok or do you want to preserve all commits? I was expecting to squash the whole branch into a single commit eventually, so it's not currently a very tidy branch...

**Comment by hsorby** [comment]
Branches and merges are preferred but perhaps we should state that in the documentation for future reference.

I typically don't squash my commits as I do like to troll through my history to find where I introduced a bug.  That being said I have squashed commits before when I have made a total mess of things.  

As far as I'm concerned it's a judgement call.  I don't mind the commit history but I will squash if have made a mess.  I try and keep my commits sane these days to avoid the temptation to squash.

**Pull request closed without merging**
